"""Initial Migration

Revision ID: 25b85863ea97
Revises: e4ff2329b679
Create Date: 2020-01-23 12:52:03.775264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b85863ea97'
down_revision = 'e4ff2329b679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book', sa.Column('day', sa.DateTime(), nullable=True))
    op.add_column('book', sa.Column('tday', sa.String(length=255), nullable=False))
    op.alter_column('book', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('book', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('book', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('book', 'tday')
    op.drop_column('book', 'day')
    op.drop_table('slots')
    # ### end Alembic commands ###
