"""Initial Migration

Revision ID: 434691ab1448
Revises: 25b85863ea97
Create Date: 2020-01-23 12:56:31.662291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434691ab1448'
down_revision = '25b85863ea97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'slots', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slots', type_='foreignkey')
    op.drop_column('slots', 'book_id')
    # ### end Alembic commands ###
