"""Initial Migration

Revision ID: bacdee33195d
Revises: 434691ab1448
Create Date: 2020-01-23 13:12:21.814593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacdee33195d'
down_revision = '434691ab1448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('slot', sa.Integer(), nullable=False))
    op.drop_column('slots', 'slots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('slots', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('slots', 'slot')
    # ### end Alembic commands ###
